package von.surface.psi

import com.intellij.lang.ASTNode
import com.intellij.psi.PsiElement
import com.intellij.psi.tree.IElementType

object VonTypes {
    @JvmField val ANNOTATION: IElementType = VonElementType("ANNOTATION")
    @JvmField val ANNOTATION_MARK: IElementType = VonElementType("ANNOTATION_MARK")
    @JvmField val ESCAPED: IElementType = VonElementType("ESCAPED")
    @JvmField val EXPORT_STATEMENT: IElementType = VonElementType("EXPORT_STATEMENT")
    @JvmField val EXPRESSION: IElementType = VonElementType("EXPRESSION")
    @JvmField val INCLUDE_STATEMENT: IElementType = VonElementType("INCLUDE_STATEMENT")
    @JvmField val INHERIT_STATEMENT: IElementType = VonElementType("INHERIT_STATEMENT")
    @JvmField val INSERT_DOT: IElementType = VonElementType("INSERT_DOT")
    @JvmField val INSERT_ITEM: IElementType = VonElementType("INSERT_ITEM")
    @JvmField val INSERT_PAIR: IElementType = VonElementType("INSERT_PAIR")
    @JvmField val INSERT_STAR: IElementType = VonElementType("INSERT_STAR")
    @JvmField val KEY_SYMBOL: IElementType = VonElementType("KEY_SYMBOL")
    @JvmField val NUMBER_SUFFIX: IElementType = VonElementType("NUMBER_SUFFIX")
    @JvmField val PAIR: IElementType = VonElementType("PAIR")
    @JvmField val PREDEFINED_SYMBOL: IElementType = VonElementType("PREDEFINED_SYMBOL")
    @JvmField val REF: IElementType = VonElementType("REF")
    @JvmField val SCOPE: IElementType = VonElementType("SCOPE")
    @JvmField val SCOPE_SYMBOL: IElementType = VonElementType("SCOPE_SYMBOL")
    @JvmField val STRING_INLINE: IElementType = VonElementType("STRING_INLINE")
    @JvmField val STRING_MULTI: IElementType = VonElementType("STRING_MULTI")
    @JvmField val STRING_PREFIX: IElementType = VonElementType("STRING_PREFIX")
    @JvmField val SYMBOL_PATH: IElementType = VonElementType("SYMBOL_PATH")
    @JvmField val TABLE: IElementType = VonElementType("TABLE")
    @JvmField val TYPE_HINT: IElementType = VonElementType("TYPE_HINT")
    @JvmField val VALUE: IElementType = VonElementType("VALUE")

    @JvmField val ACCENT: IElementType = VonTokenType("^")
    @JvmField val ANGLE_L: IElementType = VonTokenType("<")
    @JvmField val ANGLE_R: IElementType = VonTokenType(">")
    @JvmField val AS: IElementType = VonTokenType("as")
    @JvmField val AT: IElementType = VonTokenType("@")
    @JvmField val BACK_TOP: IElementType = VonTokenType("BACK_TOP")
    @JvmField val BLOCK_COMMENT: IElementType = VonTokenType("BLOCK_COMMENT")
    @JvmField val BOOLEAN: IElementType = VonTokenType("BOOLEAN")
    @JvmField val BRACE_L: IElementType = VonTokenType("{")
    @JvmField val BRACE_R: IElementType = VonTokenType("}")
    @JvmField val BRACKET_L: IElementType = VonTokenType("[")
    @JvmField val BRACKET_R: IElementType = VonTokenType("]")
    @JvmField val BYTE: IElementType = VonTokenType("BYTE")
    @JvmField val CITE: IElementType = VonTokenType("$")
    @JvmField val COLON: IElementType = VonTokenType(":")
    @JvmField val COMMA: IElementType = VonTokenType(",")
    @JvmField val COMMENT: IElementType = VonTokenType("COMMENT")
    @JvmField val DECIMAL: IElementType = VonTokenType("DECIMAL")
    @JvmField val DECIMAL_BAD: IElementType = VonTokenType("DECIMAL_BAD")
    @JvmField val DOT: IElementType = VonTokenType(".")
    @JvmField val EQ: IElementType = VonTokenType("=")
    @JvmField val ESCAPE: IElementType = VonTokenType("\\")
    @JvmField val EXPORT: IElementType = VonTokenType("@export")
    @JvmField val IMPORT: IElementType = VonTokenType("@import")
    @JvmField val INCLUDE: IElementType = VonTokenType("@include")
    @JvmField val INHERIT: IElementType = VonTokenType("@inherit")
    @JvmField val INTEGER: IElementType = VonTokenType("INTEGER")
    @JvmField val NAN: IElementType = VonTokenType("nan")
    @JvmField val NON_ESCAPE: IElementType = VonTokenType("NON_ESCAPE")
    @JvmField val NULL: IElementType = VonTokenType("null")
    @JvmField val PARENTHESIS_L: IElementType = VonTokenType("(")
    @JvmField val PARENTHESIS_R: IElementType = VonTokenType(")")
    @JvmField val QUOTATION: IElementType = VonTokenType("\"")
    @JvmField val SEMICOLON: IElementType = VonTokenType(";")
    @JvmField val SIGN: IElementType = VonTokenType("SIGN")
    @JvmField val STAR: IElementType = VonTokenType("*")
    @JvmField val STRING: IElementType = VonTokenType("STRING")
    @JvmField val SYMBOL: IElementType = VonTokenType("SYMBOL")

    object Factory {
        @JvmStatic
        fun createElement(node: ASTNode): PsiElement = when (node.elementType) {
            ANNOTATION -> VonAnnotationNode(node)
            TABLE -> VonTableNode(node)
            PAIR -> VonPairNode(node)
            VALUE -> VonValueNode(node)
            SYMBOL_PATH -> VonSymbolPathNode(node)
            else -> VonNode(node)
        }
    }
}
