package vos.surface.psi

import com.intellij.lang.ASTNode
import com.intellij.psi.PsiElement
import com.intellij.psi.tree.IElementType

object VosTypes {
    @JvmField val ANNOTATION: IElementType = VosElementType("ANNOTATION")
    @JvmField val ANNOTATION_BLOCK: IElementType = VosElementType("ANNOTATION_BLOCK")
    @JvmField val ANNOTATION_ONE: IElementType = VosElementType("ANNOTATION_ONE")
    @JvmField val ARRAY: IElementType = VosElementType("ARRAY")
    @JvmField val BOOLEAN: IElementType = VosElementType("BOOLEAN")
    @JvmField val BRACE_BLOCK: IElementType = VosElementType("BRACE_BLOCK")
    @JvmField val BRACKET_BLOCK: IElementType = VosElementType("BRACKET_BLOCK")
    @JvmField val CLASS_BLOCK: IElementType = VosElementType("CLASS_BLOCK")
    @JvmField val CLASS_BOUND: IElementType = VosElementType("CLASS_BOUND")
    @JvmField val CLASS_FIELD: IElementType = VosElementType("CLASS_FIELD")
    @JvmField val CLASS_STATEMENT: IElementType = VosElementType("CLASS_STATEMENT")
    @JvmField val COMPARE: IElementType = VosElementType("COMPARE")
    @JvmField val IDENTIFIER: IElementType = VosElementType("IDENTIFIER")
    @JvmField val INTEGER_SIGNED: IElementType = VosElementType("INTEGER_SIGNED")
    @JvmField val KEY: IElementType = VosElementType("KEY")
    @JvmField val KV_PAIR: IElementType = VosElementType("KV_PAIR")
    @JvmField val LET_STATEMENT: IElementType = VosElementType("LET_STATEMENT")
    @JvmField val MODIFIERS: IElementType = VosElementType("MODIFIERS")
    @JvmField val NAMESPACE: IElementType = VosElementType("NAMESPACE")
    @JvmField val NAMESPACE_STATEMENT: IElementType = VosElementType("NAMESPACE_STATEMENT")
    @JvmField val NULL: IElementType = VosElementType("NULL")
    @JvmField val OBJECT: IElementType = VosElementType("OBJECT")
    @JvmField val SCHEMA: IElementType = VosElementType("SCHEMA")
    @JvmField val SCHEMA_STATEMENT: IElementType = VosElementType("SCHEMA_STATEMENT")
    @JvmField val SET: IElementType = VosElementType("SET")
    @JvmField val STRING_LITERAL: IElementType = VosElementType("STRING_LITERAL")
    @JvmField val TYPE_EXPRESSION: IElementType = VosElementType("TYPE_EXPRESSION")
    @JvmField val TYPE_GENERIC: IElementType = VosElementType("TYPE_GENERIC")
    @JvmField val TYPE_GENERIC_BOUND: IElementType = VosElementType("TYPE_GENERIC_BOUND")
    @JvmField val TYPE_GENERIC_COMPARE: IElementType = VosElementType("TYPE_GENERIC_COMPARE")
    @JvmField val TYPE_GENERIC_RANGE: IElementType = VosElementType("TYPE_GENERIC_RANGE")
    @JvmField val TYPE_NUMBER: IElementType = VosElementType("TYPE_NUMBER")
    @JvmField val TYPE_SYMBOL: IElementType = VosElementType("TYPE_SYMBOL")
    @JvmField val UNION_BLOCK: IElementType = VosElementType("UNION_BLOCK")
    @JvmField val UNION_FIELD: IElementType = VosElementType("UNION_FIELD")
    @JvmField val UNION_INNER: IElementType = VosElementType("UNION_INNER")
    @JvmField val UNION_STATEMENT: IElementType = VosElementType("UNION_STATEMENT")
    @JvmField val URL_MAYBE_VALID: IElementType = VosElementType("URL_MAYBE_VALID")
    @JvmField val VALUE: IElementType = VosElementType("VALUE")

    @JvmField val ACCENT: IElementType = VosTokenType("^")
    @JvmField val ANGLE_L: IElementType = VosTokenType("<")
    @JvmField val ANGLE_R: IElementType = VosTokenType(">")
    @JvmField val ANNOTATION_MARK: IElementType = VosTokenType("#")
    @JvmField val BRACE_L: IElementType = VosTokenType("{")
    @JvmField val BRACE_R: IElementType = VosTokenType("}")
    @JvmField val BRACKET_L: IElementType = VosTokenType("[")
    @JvmField val BRACKET_R: IElementType = VosTokenType("]")
    @JvmField val BYTE: IElementType = VosTokenType("Byte")
    @JvmField val CHARACTER: IElementType = VosTokenType("CHARACTER")
    @JvmField val COLON: IElementType = VosTokenType(":")
    @JvmField val COMMA: IElementType = VosTokenType(",")
    @JvmField val COMMENT: IElementType = VosTokenType("DocumentInline")
    @JvmField val COMMENT_BLOCK: IElementType = VosTokenType("DocumentBlock")
    @JvmField val COMMENT_DOCUMENT: IElementType = VosTokenType("DocumentComment")
    @JvmField val DECIMAL: IElementType = VosTokenType("Decimal")
    @JvmField val DOLLAR: IElementType = VosTokenType("$")
    @JvmField val DOT: IElementType = VosTokenType(".")
    @JvmField val EQ: IElementType = VosTokenType("=")
    @JvmField val ESCAPE_SPECIAL: IElementType = VosTokenType("ESCAPE_SPECIAL")
    @JvmField val ESCAPE_UNICODE: IElementType = VosTokenType("ESCAPE_UNICODE")
    @JvmField val GEQ: IElementType = VosTokenType(">=")
    @JvmField val INTEGER: IElementType = VosTokenType("Integer")
    @JvmField val KW_CLASS: IElementType = VosTokenType("class")
    @JvmField val KW_DEFINE: IElementType = VosTokenType("function")
    @JvmField val KW_LET: IElementType = VosTokenType("let")
    @JvmField val KW_NAMESPACE: IElementType = VosTokenType("namespace")
    @JvmField val KW_UNION: IElementType = VosTokenType("union")
    @JvmField val LEQ: IElementType = VosTokenType("<=")
    @JvmField val PARENTHESIS_L: IElementType = VosTokenType("(")
    @JvmField val PARENTHESIS_R: IElementType = VosTokenType(")")
    @JvmField val RANGE_EQ: IElementType = VosTokenType("..=")
    @JvmField val RANGE_LE: IElementType = VosTokenType("..<")
    @JvmField val SEMICOLON: IElementType = VosTokenType(";")
    @JvmField val SIGN: IElementType = VosTokenType("SIGN")
    @JvmField val STAR: IElementType = VosTokenType("*")
    @JvmField val STRING: IElementType = VosTokenType("String")
    @JvmField val STRING_DQ: IElementType = VosTokenType("STRING_DQ")
    @JvmField val STRING_SQ: IElementType = VosTokenType("STRING_SQ")
    @JvmField val SYMBOL: IElementType = VosTokenType("Symbol")
    @JvmField val URL: IElementType = VosTokenType("Url")

    object Factory {
        @JvmStatic
        fun createElement(node: ASTNode): PsiElement = when (node.elementType) {
            ANNOTATION -> VosAnnotationNode(node)
            ANNOTATION_BLOCK -> VosAnnotationBlockNode(node)
            ANNOTATION_ONE -> VosAnnotationOneNode(node)
            ARRAY -> VosArrayNode(node)
            BOOLEAN -> VosBooleanNode(node)
            BRACE_BLOCK -> VosBraceBlockNode(node)
            BRACKET_BLOCK -> VosBracketBlockNode(node)
            CLASS_BLOCK -> VosClassBlockNode(node)
            CLASS_BOUND -> VosClassBoundNode(node)
            CLASS_FIELD -> VosClassFieldNode(node)
            CLASS_STATEMENT -> VosClassStatementNode(node)
            COMPARE -> VosCompareNode(node)
            IDENTIFIER -> VosIdentifierNode(node)
            INTEGER_SIGNED -> VosIntegerSignedNode(node)
            KEY -> VosKeyNode(node)
            KV_PAIR -> VosKvPairNode(node)
            LET_STATEMENT -> VosLetStatementNode(node)
            MODIFIERS -> VosModifiersNode(node)
            NAMESPACE -> VosNamespaceNode(node)
            NAMESPACE_STATEMENT -> VosNamespaceStatementNode(node)
            NULL -> VosNullNode(node)
            OBJECT -> VosObjectNode(node)
            SCHEMA -> VosSchemaNode(node)
            SCHEMA_STATEMENT -> VosSchemaStatementNode(node)
            SET -> VosSetNode(node)
            STRING_LITERAL -> VosStringLiteralNode(node)
            TYPE_EXPRESSION -> VosTypeExpressionNode(node)
            TYPE_GENERIC -> VosTypeGenericNode(node)
            TYPE_GENERIC_BOUND -> VosTypeGenericBoundNode(node)
            TYPE_GENERIC_COMPARE -> VosTypeGenericCompareNode(node)
            TYPE_GENERIC_RANGE -> VosTypeGenericRangeNode(node)
            TYPE_NUMBER -> VosTypeNumberNode(node)
            TYPE_SYMBOL -> VosTypeSymbolNode(node)
            UNION_BLOCK -> VosUnionBlockNode(node)
            UNION_FIELD -> VosUnionFieldNode(node)
            UNION_INNER -> VosUnionInnerNode(node)
            UNION_STATEMENT -> VosUnionStatementNode(node)
            URL_MAYBE_VALID -> VosUrlMaybeValidNode(node)
            VALUE -> VosValueNode(node)
            else -> VosNode(node)
        }
    }
}
