// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: main.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vos.lsp;

@kotlin.jvm.JvmName("-initializehelloReply")
public inline fun helloReply(block: vos.lsp.HelloReplyKt.Dsl.() -> kotlin.Unit): vos.lsp.Main.HelloReply =
  vos.lsp.HelloReplyKt.Dsl._create(vos.lsp.Main.HelloReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response message containing the greetings
 * ```
 *
 * Protobuf type `vos.lsp.HelloReply`
 */
public object HelloReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vos.lsp.Main.HelloReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vos.lsp.Main.HelloReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vos.lsp.Main.HelloReply = _builder.build()

    /**
     * `string message = 1;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun vos.lsp.Main.HelloReply.copy(block: vos.lsp.HelloReplyKt.Dsl.() -> kotlin.Unit): vos.lsp.Main.HelloReply =
  vos.lsp.HelloReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

